In [1]:
import pandas as pd

In [3]:
data={"name":["abbas ","bilal","sulieman","gulali"],"age":[23,26,27,35],"sex":["male","male","male","female"]}

In [6]:

df=pd.DataFrame(data)

In [7]:
df

       name  age     sex
0    abbas    23    male
1     bilal   26    male
2  sulieman   27    male
3    gulali   35  female

In [8]:
df['age'].max()

np.int64(35)

In [10]:
df.describe()

             age
count   4.000000
mean   27.750000
std     5.123475
min    23.000000
25%    25.250000
50%    26.500000
75%    29.000000
max    35.000000

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   sex     4 non-null      str
dtypes: int64(1), str(2)
memory usage: 271.0 bytes

In [13]:
pd.Series([1,2,3,4,5,6,7,8,9],name="age")

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: age, dtype: int64